apiVersion: v1
kind: ConfigMap

metadata:
 name: {{ include "example-service.fullname" . }}
 namespace: {{ .Values.namespace }}

data:
  {{- range $key, $value := .Values.serviceConfig }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
