apiVersion: v1
kind: Secret

metadata:
   name: {{ include "example-service.fullname" . }}
   namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
